Fixes python2/3 compatability for unicode
This resolves implicit casts of python strings to unicode by explicit
casts to `str` to mitigate errors in calls to vtk of form

```
  File "/lustre/scratch4/turquoise/.mdt1/pwolfram/pwolfram/Delaware_inundation/USDEQU300cr1/MPAS-Tools/visualization/paraview_vtk_field_extractor/utils.py", line 592, in write_vtp_header
    vtkFile.openElement("Points")
  File "/users/pwolfram/lib/python2.7/site-packages/evtk/vtk.py", line 472, in openElement
    self.xml.openElement(tagName)
  File "/users/pwolfram/lib/python2.7/site-packages/evtk/xml.py", line 48, in openElement
    self.stream.write(str.encode(st))
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'
```